### ISSUE TITLE
https://www.apiseven.com/en/career 改为 https://www.apiseven.com/en/careers

### ISSUE THREAD

**Issue by moonming** [api7/website#110]
之前放到外面的都是 https://www.apiseven.com/en/careers

**Comment by juzhiyuan** [comment]
cc @guoqqqi 修改下路由吧。

**Comment by juzhiyuan** [comment]
1. 把 `/pages/career` 改为 `/pages/careers`；
2. 全局搜索代码内的 `/career` 关键词，修改为 `/careers`；
