### ISSUE TITLE
职位： 商务拓展经理

### ISSUE THREAD

**Issue by membphis** [api7/website#134]
------------------------职位信息如下：

岗位职责：
1、根据公司业务发展需求，寻找、挖掘有利于公司的合作资源，评估资源的可合作性；
2、负责对商务客户的管理和维护，独立高效地完成商务谈判、跟进、签约、合作落地、合同款项收付、客户关系维护等工作，达成业绩指标；
3、负责商务客户的维护，定期收集商业产品端的受众反馈，及时反馈给公司进行产品调整优化；
4、关注商务客户的动销情况，销售数据收集统计与分析。收集客户需求，为客户提供专业支持与服务，针对其销售、运营情况，提出合理化建议；
5、完成上级安排的其他工作。

任职要求：
1、本科及以上学历，具备良好远程协作能力，能有效的利用渠道资源；
2、了解开源文化，熟悉 API 网关、负载均衡产品等产品更佳；
3、优秀的商务谈判能力、协调能力和营销能力，能够独立完成营销工作。具备一定的抗压能力，有团队合作意识，有较强的执行力；
4、处事灵活，工作细致，逻辑思维能力强，具备处理突发事件能力。

**Comment by membphis** [comment]
@juzhiyuan 本周放到公司官网即可

**Comment by juzhiyuan** [comment]
@membphis 需要英文不？

cc @guoqqqi 处理下吧

**Comment by guoqqqi** [comment]
OK 分配给我吧
