### ISSUE TITLE
“新闻报道“页面

### ISSUE THREAD

**Issue by moonming** [api7/website#137]
- [x] 英文版本
- [x] 新闻列表商标图
- [ ] 视频资料归属

**Comment by moonming** [comment]
refer to https://pingcap.com/about-cn/news/

**Comment by moonming** [comment]
- 2020 年 12 月 2 日： APISIX 温铭：开源的本质是要拿开发者的杠杆｜人物志 https://blog.csdn.net/csdnnews/article/details/110508201
- 2020 年 10 月 29 日：API Security Gateway – Using APISIX in the EFPF Platform   https://www.efpf.org/post/api-security-gateway-using-apisix-in-the-efactory-platform
- 2020 年 8 月 3 日：APISIX: An Open Source API Gateway for Microservices https://thenewstack.io/apisix-an-open-source-api-gateway-for-microservices/
- 2020 年 7 月 20 日：Apache 顶级项目 APISIX VP 温铭：本土开源不能只靠建一个软件基金会丨开源创新30人 https://www.infoq.cn/article/9tov5eAezjqcBIe3j753
- 2020 年 7 月 16 日： APISIX 毕业成为 Apache 软件基金会顶级项目 https://www.infoq.cn/article/CI9dj3A0iEHbm885eED5
- 2020 年 7 月 15 日： APISIX 专访：9个月成 ASF 顶级项目，开源可以带来付费用户 https://www.oschina.net/question/4489239_2317670
- 2020 年 7 月 9 日：Apache APISIX 的快速孵化之旅 https://alc-beijing.github.io/alc-site/post/podcast/episode-3-the-story-of-apisix-fulltext/
- 2020 年 2 月 21 日：温铭：运营开源社区、基础软件创业-拒绝自嗨、聚焦和快速发布 https://blog.csdn.net/kaiyuanshe/article/details/104438331
- 2019 年 11 月 13 日： SD Times Open-Source Project of the Week: Apache APISIX  https://sdtimes.com/micro/sd-times-open-source-project-of-the-week-apache-apisix/
- 2019 年 10 月 25 日： APISIX 进入 Apache 孵化器 https://www.infoq.cn/article/rxo9cfer7pwvd1h8wcmt

视频资料：
- https://www.bilibili.com/video/av627161961/
- https://www.youtube.com/watch?v=iEegNXOtEhQ
等

**Comment by juzhiyuan** [comment]
@moonming  目前只剩下俩视频了，视频嵌到 博客 里如何？

**Comment by juzhiyuan** [comment]
或者，之后应当有一个「资源区」。

**Comment by moonming** [comment]
ok
Thanks,
Ming Wen
Twitter: _WenMing


琚致远 <notifications@github.com> 于2020年12月14日周一 上午11:24写道：

**Comment by juzhiyuan** [comment]
@guoqqqi 新建两篇博客吧，把视频嵌入进去。
