### ISSUE TITLE
《 思必驰：为什么我们重新写了一个 k8s ingress controller？》漏掉了部分图片

### ISSUE THREAD

**Issue by juzhiyuan** [api7/website#147]
https://www.apiseven.com/zh/usercase/aispeech

![image](https://user-images.githubusercontent.com/2106987/101982829-97e24b00-3cb1-11eb-978a-1a1a272ca073.png)

@guoqqqi 请检查原文是否有。

**Comment by guoqqqi** [comment]
原文没有，迁移后的内容均与原文保持一致。

**Comment by juzhiyuan** [comment]
OK，@gxthrj 请提供下原图。

**Comment by guoqqqi** [comment]
对不起，是我搞错了，原文中的图片链接因为失效所以未显示。我会提一个PR来修复它！
