### ISSUE TITLE
文字显示错位

### ISSUE THREAD

**Issue by bzp2010** [api7/website#266]
较小屏幕中[此页面](https://www.apiseven.com/zh/products/api7/features)文字显示会出现错位，如下图所示
![image](https://user-images.githubusercontent.com/8078418/132280765-8dec1252-5c97-40e9-aaab-33253d278912.png)

**Comment by guoqqqi** [comment]
Hi, @Ylikj Can you help with this problem?

**Comment by Ylikj** [comment]
Okkkkkk~
