### ISSUE TITLE
features页面，页面最小时，点击切换标题栏切换出错

### ISSUE THREAD

**Issue by Ylikj** [api7/website#276]
![Snipaste_2021-09-08_18-08-14](https://user-images.githubusercontent.com/26732418/132491553-bd64ba52-b7b2-419e-ba51-baed38393eda.png)
如图，当我点击某一标题时，极大概率会出现另一标题被选中的情况，每个标题都有可能出现这种情况，并不特定

**Comment by juzhiyuan** [comment]
@Ylikj Would you like to have a try?

**Comment by Ylikj** [comment]
yeah

**Comment by Ylikj** [comment]
@juzhiyuan Can I submit documents like this ？

**Comment by juzhiyuan** [comment]
Submit what documents?

**Comment by Ylikj** [comment]
I delete it,please check #292 pr
