### ISSUE TITLE
优化导航新增技术博客二级导航

### ISSUE THREAD

**Issue by guoqqqi** [api7/website#314]
1. 在【技术博客】标签下增加【技术文章】【用户案例】效果如：
![image](https://user-images.githubusercontent.com/72343596/134801935-d32c38e5-6d35-4881-960a-df0f7a3db6f9.png)
2. 文案如下：
【技术文章】阅读技术文章，了解前沿技术
【用户案例】阅读全球领先企业与深圳支流科技的故事
3. 相关资源中的【用户案例】移除

**Comment by Ylikj** [comment]
Let me try
