### ISSUE TITLE
Change the English time format of the article page.

### ISSUE THREAD

**Issue by guoqqqi** [api7/website#33]
The current time format of the English and Chinese article pages is the same and should be corrected to:
1. Chinese pages: year/month/day;
2. English pages: day/month/year.

![image](https://user-images.githubusercontent.com/72343596/112173742-cf597f80-8c30-11eb-8ce3-f1a69ee390cc.png)
![image](https://user-images.githubusercontent.com/72343596/112173630-b4870b00-8c30-11eb-9772-fb1b6cb9b299.png)

**Comment by juzhiyuan** [comment]
yes, for Chinese, use `YYYY-MM-DD`; for others, use `DD-MM-YYYY`

**Comment by juzhiyuan** [comment]
any update?
