### ISSUE TITLE
blog: "Apache APISIX 助力企业数字化转型" 问题

### ISSUE THREAD

**Issue by membphis** [api7/website#4]
![image](https://user-images.githubusercontent.com/6814606/107137683-de6ac380-6949-11eb-8b89-111724df6278.png)
更正为：
![image](https://user-images.githubusercontent.com/6814606/107137709-0f4af880-694a-11eb-9a2a-51b2761ff86d.png)

![image](https://user-images.githubusercontent.com/6814606/107137716-1b36ba80-694a-11eb-9cb2-b1cb225a866b.png)
更正为：
![image](https://user-images.githubusercontent.com/6814606/107137723-2b4e9a00-694a-11eb-8230-12cde7bef0e1.png)

**原文章**：https://shimo.im/docs/sH0Y4vbQUXcv0oyl

**Comment by membphis** [comment]
need your help @juzhiyuan

**Comment by juzhiyuan** [comment]
OK
