### ISSUE TITLE
文章分类页，如：用户案例

### ISSUE THREAD

**Issue by juzhiyuan** [api7/website#5]
- [ ] 根据参数渲染内容：page & pageSize & category
- [ ] 布局、样式

**Comment by moonming** [comment]
http://www3.apiseven.com/category/%e7%94%a8%e6%88%b7%e6%a1%88%e4%be%8b/ 需要迁移

**Comment by juzhiyuan** [comment]
yes

**Comment by moonming** [comment]
ping

**Comment by juzhiyuan** [comment]
参考：https://pingcap.com/cases-cn/

**Comment by juzhiyuan** [comment]
需要一个文章列表页，不然没访问入口。

cc @moonming 

开发 cc @guoqqqi @juzhiyuan

**Comment by juzhiyuan** [comment]
1. 新建一个 `PostList` 页面；
2. 新建两个路由：
  a. `/usercases`；
  b. `/blog`
3. 两个路由均指向 PostList 页。

我先做一个模板，然后 @guoqqqi 来修改。

**Comment by juzhiyuan** [comment]
https://github.com/api7/website/pull/152/files

@guoqqqi 你可以看下这个 PR 是怎么做到动态获取 posts 目录下的文章列表的，现在需要由你继续参考 https://pingcap.com/cases-cn/ 制作样式，记得更新本地的 master 分支。
