### ISSUE TITLE
招聘页 URL 动态变化

### ISSUE THREAD

**Issue by juzhiyuan** [api7/website#56]
在英文页面的招聘列表页中，点击查看详情第一次会显示中文内容，刷新后变为英文内容，与 #28 有关。

https://www.apiseven.com/en/career

cc @moonming @LiteSun @membphis

**Comment by membphis** [comment]
难道因为我的默认语言是英文？没看到这个 bug 。

Is it because my default language is English? Not found this bug.

**Comment by juzhiyuan** [comment]
> 难道因为我的默认语言是英文？没看到这个 bug 。
> 
> Is it because my default language is English? Not found this bug.

是的哈

**Comment by juzhiyuan** [comment]
此外，招聘详情页其实是复用了文章页面，文章页面目前没有专门设计样式（但是支持多种语言代码高亮），这块儿会低优先级处理。
