### ISSUE TITLE
首页 增加 可信开源项目评估证书

### ISSUE THREAD

**Issue by juzhiyuan** [api7/website#90]
![image](https://user-images.githubusercontent.com/2106987/99353135-e2ed8600-28de-11eb-9d5b-b2e5163bd58b.png)

追加在上方红色圆圈后，点击后跳转到详情页。

## 内容

讨论链接（内部）：https://api7ai.slack.com/archives/C01EHEFJ74J/p1605578102000300

![image](https://user-images.githubusercontent.com/2106987/99353181-fd276400-28de-11eb-85a9-ec2695cfb501.png)

**Comment by moonming** [comment]
这个图片就行了？点击跳转到哪里呢？

**Comment by moonming** [comment]
哦，懂了。你设计就行了

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/99635406-e585e200-2a7c-11eb-99b7-8e0ae3c993ab.png)

cc @moonming ，文案 **厂商** 是否合适？信通院不属于厂商吧？

**Comment by moonming** [comment]
不属于。
获得厂商和权威机构认证

Thanks,
Ming Wen
Twitter: _WenMing


琚致远 <notifications@github.com> 于2020年11月19日周四 下午3:36写道：

**Comment by juzhiyuan** [comment]
cc @guoqqqi 请修改下描述。
