### ISSUE TITLE
增加招聘职位，排在第一排

### ISSUE THREAD

**Issue by moonming** [api7/website#93]
**增长团队负责人**
职责：
1. 开源社区和公司商业产品在全球的市场和运营
2. 销售线索的梳理、跟进和优化
3. 竞品和行业分析
4. 搭建市场、运营等增长团队

要求：
1. 沟通能力强，积极主动
2. 对数据敏感
3. 有 3 年以上 toB 增长经验，有国际化经验优先
4. 英文口语流利，有海外媒体、咨询公司经验优先
5. 有参与过开源社区运营优先

**Head of Growth**
Responsibilities:
1. Growthing of open source communities and company commercial products
2. Sort out, follow up and optimize sales leads
3. Competitive products and industry analysis
4. Build growth team

Requirements:
1. Strong communication skills and proactive
2. Sensitive to data
3. More than 3 years of toB growth experience, international experience is preferred
4. Fluent oral English, experience in overseas media and consulting companies is preferred
5. Have participated in open source community is preferred

**Comment by juzhiyuan** [comment]
cc @guoqqqi
